### ISSUE TITLE
Instructions of how to obtain libsdl is missing

### ISSUE THREAD

**Issue by soegaard** [stonecauldron/racket-sdl#3]
Hi,

I was looking into using SDL2 on OS X and ran into problems.
First I installed libsdl from https://libsdl.org/download-2.0.php#source
Then I installed the package racket-sdl.
Finally I opened and ran lazyfoo01.rkt in DrRacket.
The error I get is:
    ffi-lib: couldn't open "libSDL2.dylib" (dlopen(libSDL2.dylib, 6): image not found)

It seems that the installer installs a Framework:
    mbp:lazyfoo soegaard$ ls /Library/Frameworks/SDL2.framework/
    Headers		Resources	SDL2		Versions

There does not seem to be a dylib in the framework.

Question: Where can I get libSDL2.dylib ?

**Comment by soegaard** [comment]
Fetching the source and building the shared library in XCode worked.
The attached zip-file contains a build of libSDL 2.05 build on macOS Sierra 10.12.2.

[libSDL2.dylib.zip](https://github.com/stonecauldron/racket-sdl/files/680034/libSDL2.dylib.zip)

**Comment by stonecauldron** [comment]
Have you tried installing sdl2 with homebrew? I think it comes in a dylib format.

**Comment by johannesl** [comment]
No need to compile the source actually.

After you install the SDL2 runtime dmg, you can use this trick:
`ln -s /Library/Frameworks/SDL2.framework/SDL2 /usr/local/lib/libSDL2.dylib`
